KidsLand/Controllers/ContactsController.cs
using System.Web.Mvc;

namespace KidsLand.Controllers
{
    public class ContactsController : Controller
    {
        // GET: Contacts
        public ActionResult ContactsIndex()
        {
            return View();
        }
    }
}

KidsLand/Controllers/HomePageController.cs
using System.Linq;
using System.Web.Mvc;
using KidsLand.Models.EF;
using KidsLand.Models.ViewModels;
using NLog;

namespace KidsLand.Controllers
{
    public class HomePageController : Controller
    {
        public static readonly Logger logger = LogManager.GetCurrentClassLogger();
        //
        // GET: /HomePage/
        public ActionResult Index()
        {
            logger.Info("Look home page");
            var mpvm = new MainPageViewModel();
            var context = new KidsLandIdentityContext();
            mpvm.NewsList = context.News.OrderByDescending(x => x.NewsDate).Take(2).ToList();
            return View(mpvm);
        }
	}
}

KidsLand/Controllers/InterestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KidsLand.Controllers
{
    public class InterestController : Controller
    {
        // GET: Interest
        public ActionResult InterestIndex()
        {
            return View();
        }
    }
}

KidsLand/Controllers/LogopedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KidsLand.Controllers
{
    public class LogopedController : Controller
    {
        // GET: Logoped
        public ActionResult Index()
        {
            return View();
        }
    }
}

KidsLand/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

KidsLand/Views/Shared/_LayoutExtended.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>@ViewBag.Title</title>
	<meta http-equiv="X-UA-Compatible" content="IE=8;FF=3;OtherUA=4" />
	@*<meta name="copyright" content="© 2011" />
	<meta name="Robots" content="all" />
	<meta name="document-state" content="dynamic" />
	<meta name="revisit" content="7 days" />
	<meta name="revisit-after" content="7 days" />
	<meta http-equiv="Pragma" content="no-cache" />
	<meta name="viewport" content="width=device-width" />
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="Cache-Control" content="no-cache" />
	<meta name="description" content="описание сайта" />
	<meta name="keywords" content="ключевые слова сайта" />
	<link rel="Shortcut Icon" href="@Url.Content("~/favicon.ico")" />*@
	<link href="@Url.Content("/Content/Site.css")" rel="stylesheet" type="text/css" />
	@*<link href="@Url.Content("/Content/themes/jquery-ui-1.8.21.custom.css")" rel="stylesheet" type="text/css" />*@
	@RenderSection("header", false)
</head>
<body>
	<div class="page">
		<header>
			<div id="title">
				<h1>Заголовок</h1>
			</div>
			<div id="logindisplay">
			@Html.Partial("_LogOnPartial")
		</div>
			<nav>
				<ul id="menu">
					<li>@Html.ActionLink("Главная", "index", "home")</li>
					<li>@Html.ActionLink("О проекте", "about", "home")</li>
				</ul>
			</nav>
		</header>
		<div id="main">
			@RenderBody()
		</div>
		<footer>все права защищены @( DateTime.Now.Year.ToString())	© компания<br/>
			программирование <a href="#">название компания</a></footer>
	</div>
	@Content.Scripts("jquery-1.7.2.min.js", Url)
	@Content.Scripts("jquery.unobtrusive-ajax.min.js", Url)
	@Content.Scripts("modernizr-2.5.3.js", Url)
	@*@Content.Scripts("jquery-ui-1.8.21.custom.min.js", Url)*@
	@RenderSection("scripts", false)
	@Html.WriteScriptBlocks()
</body>
</html>

KidsLand/Views/Shared/_LayoutMenu.cshtml
@using KidsLand.Controllers
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "_LayoutMenu";
}
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
<script src="~/Scripts/hoverIntent.js"></script>

<div id="bg-top">
    <div class="container">
        <header>
            <div class="row top">
                <div class="span3">
                    <div class="clearfix">
                        <div class="clearfix header-block-pad">
                            <a href="@Url.Action("Index", "HomePage")">
                                <img src="@Url.Content("~/Content/img/logo.png")"  alt=""/>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="span7">
                    <p class="phone">
                        We always care about your child! Call us:  
                        <span>1 800 123 4567</span>
                    </p>
                </div>
                <div class="span2">
                    @if (User.Identity.GetUserName().Equals(string.Empty))
                    {
                        <button onclick=" location.href = '@Url.Action("Login", "Account")';return false; " class=" btn mybtn">Log in</button>
                        <button onclick=" location.href = '@Url.Action("Register", "Account")';return false; " class=" btn btn-primary signinbtn">Sign in</button>
                    }
                    else
                    {
                        <div>
                            <div class="user-name">@User.Identity.GetUserName()</div>
                            <button onclick=" location.href = '@Url.Action("LogOff", "Account")';return false; " class=" btn btn-primary signinbtn">Log off</button>
                        </div>
                    }
                </div>
                
            </div>
            <div id="nav_section">
                <div class="row">
                    <div class="span12">
                        <div class="navbar navbar_ clearfix">
                            <div class="navbar-inner navbar-inner_">
                                @*<a class="menu btn-navbar" data-target=".nav-collapse_" data-toggle="collapse">MENU</a>*@
                                <div class="nav-collapse nav-collapse_ collapse">
                                    <span class="line"></span>
                                    <ul class="nav sf-menu">
                                        <li>@Html.ActionLink("О нас", "Index", "AboutUs", null, new { @class = "push-up-button" })
                                            <ul style="display: none;">
                                                <li>@Html.ActionLink("История", "TeachersIndex", "Teachers")</li>
                                                <li>@Html.ActionLink("Нормативные документы", "Documents", "AboutUs")</li>
                                                <li>@Html.ActionLink("Педагоги", "TeachersIndex", "Teachers")</li>
                                                <li><a href="#">Наши достижения</a></li>
                                                <li><a href="#">Контакты</a></li>
                                                @if (User.Identity.IsAuthenticated)
                                                {
                                                    if (User.IsInRole("Admin"))
                                                    {
                                                        <li>@Html.ActionLink("Кабинет администратора","Index","Admin")</li>
                                                    }
                                                }
                                            </ul></li>
                                        <li>@Html.ActionLink("Логопед", "Index", "Logoped", null, new { @class = "push-up-button" })</li>
                                        <li class=""><a href="#" style="font-size: 22px;"> Психолог </a>
                                            <ul style="display: none;">
                                                <li><a href="#"> Ерунда </a></li>
                                                <li class="has-ul">
                                                    <a href="#"> Recent projects</a>
                                                    <ul style="display: none;">
                                                        <li><a href="#"> Project 1</a></li>
                                                        <li><a href="#"> Project 2</a></li>
                                                        <li><a href="#"> Project 3</a></li>
                                                    </ul>
                                                </li>
                                                <li><a href="#"> Childcare</a></li>
                                                <li><a href="#"> Education</a></li>
                                                <li><a href="#"> Page not found (404)</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="#" class="push-up-button"> Доп. образование </a></li>
                                        <li>
                                            @*@Html.ActionLink("Обр.&nbsp;деятельность", "InterestIndex", "Interest", null, new { @class = "push-up-button" })*@
                                            <a href="#" title="Образовательная деятельность">Обр.&nbsp;деятельность</a>
                                        </li>
                                        <li>
                                            @*@Html.ActionLink("Контакты", "ContactsIndex", "Contacts", null, new { @class = "push-up-button" })*@
                                            <a href="#">Здоровьесбережение</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    </div>
    @RenderBody()
    <footer>
        <div class="bg_center_footer">
            <div class="container">
                <div class="row">
                    <div class="span11">
                        <ul>
                            <li>
                                @Html.ActionLink("О нас", "Index", "AboutUs")
                            </li>
                            <li> @Html.ActionLink("Логопед", "Index", "Logoped")</li>
                            <li><a href="#">Психолог</a> </li>
                            <li><a href="#">Доп. образование</a></li>
                            <li><a href="#" title="Образовательная деятельность">Образователь. деятельность</a></li>
                            <li><a href="#">Здоровьесбережение</a></li>
                        </ul>
                        <div class="clearfix">
                        </div>
                        <p>                            Copyright © 2013. All rights reserved.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</div>

<script>

    jQuery(document).ready(function () {
        jQuery('ul.sf-menu').superfish();
    });

</script>






KidsLand/Views/Shared/_LayoutMenuAdmin.cshtml
@using KidsLand.Controllers
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "_LayoutMenu";
}
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")

<script src="~/Scripts/hoverIntent.js"></script>

<div id="bg-top">
    <div class="container">
        <header>
            <div class="row top">
                <div class="span3">
                    <div class="clearfix">
                        <div class="clearfix header-block-pad">
                            <a href="@Url.Action("Index", "HomePage")">
                                <img src="@Url.Content("~/Content/img/logo.png")" alt="" />
                            </a>
                        </div>
                    </div>
                </div>
                <div class="span7">
                    <p class="phone">
                        We always care about your child! Call us:
                        <span>1 800 123 4567</span>
                    </p>
                </div>
                <div class="span2">
                    @if (User.Identity.GetUserName().Equals(string.Empty))
                    {
                        <button onclick=" location.href='@Url.Action("Login", "Account")' ;return false; " class=" btn mybtn">Log in</button>
                        <button onclick=" location.href='@Url.Action("Register", "Account")' ;return false; " class=" btn btn-primary signinbtn">Sign in</button>
                    }
                    else
                    {
                        <div>
                            <div class="user-name">@User.Identity.GetUserName()</div>
                            <button onclick=" location.href='@Url.Action("LogOff", "Account")' ;return false; " class=" btn btn-primary signinbtn">Log off</button>
                        </div>
                    }
                </div>

            </div>
            <div id="nav_section">
                <div class="row">
                    <div class="span12">
                        <div class="navbar navbar_ clearfix">
                            <div class="navbar-inner navbar-inner_">
                                @*<a class="menu btn-navbar" data-target=".nav-collapse_" data-toggle="collapse">MENU</a>*@
                                <div class="nav-collapse nav-collapse_ collapse">
                                    <span class="line"></span>
                                    <ul class="nav sf-menu">
                                        <li>
                                            @Html.ActionLink("О нас", "Index", "AboutUs", null, new { @class = "push-up-button" })
                                            <ul style="display: none;">
                                                <li>@Html.ActionLink("История", "TeachersIndex", "Teachers")</li>
                                                <li>@Html.ActionLink("Нормативные документы", "Documents", "AboutUs")</li>
                                                <li>@Html.ActionLink("Педагоги", "TeachersIndex", "Teachers")</li>
                                                <li><a href="#">Наши достижения</a></li>
                                                <li><a href="#">Контакты</a></li>
                                                @if (User.Identity.IsAuthenticated)
                                                {
                                                    if (User.IsInRole("Admin"))
                                                    {
                                                        <li>@Html.ActionLink("Кабинет администратора", "Index", "Admin")</li>
                                                    }
                                                }
                                            </ul>
                                        </li>
                                        <li>@Html.ActionLink("Логопед", "Index", "Logoped", null, new { @class = "push-up-button" })</li>
                                        <li class="">
                                            <a href="#" style="font-size: 22px;"> Психолог </a>
                                            <ul style="display: none;">
                                                <li><a href="#"> Ерунда </a></li>
                                                <li class="has-ul">
                                                    <a href="#"> Recent projects</a>
                                                    <ul style="display: none;">
                                                        <li><a href="#"> Project 1</a></li>
                                                        <li><a href="#"> Project 2</a></li>
                                                        <li><a href="#"> Project 3</a></li>
                                                    </ul>
                                                </li>
                                                <li><a href="#"> Childcare</a></li>
                                                <li><a href="#"> Education</a></li>
                                                <li><a href="#"> Page not found (404)</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="#" class="push-up-button"> Доп. образование </a></li>
                                        <li>
                                            @*@Html.ActionLink("Образов. деятельность", "InterestIndex", "Interest", null, new { @class = "push-up-button" })*@
                                            <a href="#" title="Образовательная деятельность">Обр.&nbsp;деятельность</a>
                                        </li>
                                        <li>
                                            @*@Html.ActionLink("Контакты", "ContactsIndex", "Contacts", null, new { @class = "push-up-button" })*@
                                            <a href="#">Здоровьесбережение</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    </div>
    <div class="menu-block">
        <nav class="navbar navbar-inverse" role="navigation">
            <div class="container">
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        @*<li><a href="#">Новости</a></li>*@
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Новости<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="@Url.Action("News","News")">Все</a></li>
                                <li><a href="@Url.Action("CreateNews","News")">Создать</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                                <li class="divider"></li>
                                <li><a href="#">One more separated link</a></li>
                            </ul>
                        </li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </div>
@RenderBody()
<footer>
    <div class="bg_center_footer">
        <div class="container">
            <div class="row">
                <div class="span11">
                    <ul>
                        <li>
                            @Html.ActionLink("О нас", "Index", "AboutUs")
                        </li>
                        <li> @Html.ActionLink("Логопед", "Index", "Logoped")</li>
                        <li><a href="#">Психолог</a> </li>
                        <li><a href="#">Доп. образование</a></li>
                        <li><a href="#" title="Образовательная деятельность">Образователь. деятельность</a></li>
                        <li><a href="#">Здоровьесбережение</a></li>
                    </ul>
                    <div class="clearfix">
                    </div>
                    <p>
                        Copyright © 2013. All rights reserved.
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>
</div>

<script>

    jQuery(document).ready(function () {
        jQuery('ul.sf-menu').superfish();
    });

</script>




