KidsLand/Controllers/AboutUs/AboutUsController.cs
using System.Web.Mvc;

namespace KidsLand.Controllers.AboutUs
{
    public class AboutUsController : Controller
    {
        // GET: AboutUs
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Documents()
        {
            return View("~/Views/AboutUs/Documents.cshtml");
        }

    }
}

KidsLand/Controllers/AboutUs/TeachersController.cs
using System.Web.Mvc;
using KidsLand.Models;
using KidsLand.Models.EF;
using Microsoft.AspNet.Identity.EntityFramework;

namespace KidsLand.Controllers.AboutUs
{
    public class TeachersController : Controller
    {
        // GET: Teachers
        public ActionResult TeachersIndex()
        {
            var store = new UserStore<ApplicationUser>(new KidsLandIdentityContext()) { AutoSaveChanges = false };
            
            return View("~/Views/AboutUs/TeacherView.cshtml");
        }
    }
}

KidsLand/Controllers/HomePageController.cs
using System.Linq;
using System.Web.Mvc;
using KidsLand.Models.EF;
using KidsLand.Models.ViewModels;
using NLog;

namespace KidsLand.Controllers
{
    public class HomePageController : Controller
    {
        public static readonly Logger logger = LogManager.GetCurrentClassLogger();
        //
        // GET: /HomePage/
        public ActionResult Index()
        {
            logger.Info("Look home page");
            var mpvm = new MainPageViewModel();
            var context = new KidsLandIdentityContext();
            mpvm.NewsList = context.News.OrderByDescending(x => x.NewsDate).Take(2).ToList();
            return View(mpvm);
        }
	}
}

KidsLand/Views/AboutUs/Documents.cshtml
@{
    ViewBag.Title = "Documents";
    Layout = "~/Views/Shared/_LayoutMenu.cshtml";
}

<div class="container">
    <p class="breadcrumb">
        <div class="normal-font20">
            @Html.ActionLink("Главная", "Index", "HomePage")
            > Нормативные документы
        </div>
    </p>
</div>

<section id="content">
<div class="container">
    <div class="row">
        <div class="head-title">Нормативные документы</div>
        
        <div class="ul-vertical">
            <ol class="ul-vertical">
                <li><a href="~/Content/Documents/Положение о дошкольном отделении.pdf">Положение о дошкольном отделении</a></li>
                <li><a href="~/Content/Documents/Положение о личном деле.pdf">Положение о личном деле</a></li>
                <li><a href="~/Content/Documents/Положение о системе внутр.мониторинга КО.pdf">Положение о системе внутр.мониторинга КО</a></li>
                <li><a href="~/Content/Documents/Порядок организации ОД 2014.pdf">Порядок организации ОД 2014</a></li>
                <li><a href="~/Content/Documents/Правила приема и отчисления 2014.pdf">Правила приема и отчисления 2014</a></li>
            </ol>
        </div>
    </div>
</div>
</section>

KidsLand/Views/AboutUs/Index.cshtml

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutMenu.cshtml";
}
<div class="build-in-content">
    <p class="breadcrumb">
        <div class="normal-font20">

            @Html.ActionLink("Главная", "Index", "HomePage")
            > О нас
        </div>
    </p>

    <h2>Информация о нас</h2>

</div>

KidsLand/Views/AboutUs/TeacherView.cshtml

@{
    ViewBag.Title = "TeacherView";
    Layout = "~/Views/Shared/_LayoutMenu.cshtml";
}

@*@Styles.Render("~/Content/jcarousel-style.css")*@
@Styles.Render("~/Content/jcarousel.basic.css")
@Scripts.Render("~/Scripts/jquery.jcarousel.min.js")
@Scripts.Render("~/Scripts/jcarousel.basic.js")

<div class="container">
    <p class="breadcrumb">
        <div class="normal-font20">
            @Html.ActionLink("Главная", "Index", "HomePage")
            @Html.ActionLink(" > О нас ", "Index", "AboutUs")
            > Педагоги
        </div>
    </p>
</div>    

<section id="content">
    <div class="container">
        <div class="row">
            <div class="span8">
                <h1>Наши преподаватели</h1>
                <div style="width: 750px;">
                    <div class="wrapper">
                      
                        <div class="jcarousel-wrapper">
                            <div class="jcarousel">
                                <ul>
                                    <li>
                                        <div class="example3">
                                            <img src="~/Content/img/Teachers/Antropova.jpg" alt="">
                                            <div class="example_text">
                                                <h6>Антропова Тамара Андреевна</h6>
                                                    <span>Должность</span>
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="example3">
                                            <img src="~/Content/img/Teachers/Ogolihina.jpg" alt="">
                                            <div class="example_text">
                                                <h6>Оголихина Лариса Борисовна</h6>
                                                <span>Должность</span>
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="example3">
                                            <img src="~/Content/img/Teachers/Vilkova.jpg" alt="">
                                            <div class="example_text">
                                                <h6>Вилкова Татьяна Витальевна</h6>
                                                <span>Должность</span>
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="example3">
                                            <img src="~/Content/img/Teachers/volkova.jpg" alt="">
                                            <div class="example_text">
                                                <h6>Волкова Татьяна Анатольевна</h6>
                                                <span>Должность</span>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>

                            <a href="#" class="jcarousel-control-prev">&lsaquo;</a>
                            <a href="#" class="jcarousel-control-next">&rsaquo;</a>

                            <p class="jcarousel-pagination">

                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="span14">
                <div class="latest">
                    <h3>Latest news</h3>
                    <p>
                        <b>24 0f January 2014</b>
                        Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.
                        <a href="#">more ></a>
                    </p>
                    <p>
                        <b>24 0f January 2014</b>
                        Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.
                        <a href="#">more ></a>
                    </p>
                    <p>
                        <b>24 0f January 2014</b>
                        Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.
                        <a href="#">more ></a>
                    </p>
                    <a class="arhive" href="#">news arhive <em>→</em></a>
                    <div class="clearfix padcontent_small"></div>
                </div>
                <div class="clearfix padcontent"></div>
                <div class="offers">
                    <h4>Special Offer</h4>

                </div>
            </div>
            <div class="clearfix padcontent"></div>
        </div>
    </div>
</section>

<script>
    $(function () {
        $('.jcarousel').jcarousel({
            // Configuration goes here
        });
    });
</script>